development:
  adapter: postgresql
  database: salao2
  username: postgres
  password: postgres

test:
  adapter: postgresql
  database: salao2
  username: postgres
  password: postgres

production:
  adapter: postgresql
  database: salao
  username: salao
  password: salao*&098

