# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9129fa9cb8c2cbb9b84b098dc011495114015225ecfbc99aae4c2836393f481c40225539d4bc00b85644b1af5f55d4f3233d18d930d34a88091f3d5feaa9c89

test:
  secret_key_base: c71595b969a953d55092c6e0af7dcd2051e057985f64b5bd26ea78ffdd94e302f9fbfdb9655504422b5384974349983859092c043bdc9caaec0606a3724ec519

# Do not keep production secrets in the repository,
# # instead read values from the environment.
production:
   secret_key_base: 6dd31c09ad6f312a36f745e9aa82ee2d4648a8f842a1e73e837ef1b22171df3cd888e5666eb0dff03a8e9bc343dc2d95e763340435610e382f94b79eb5c2c639

